"use client";

import { useState } from "react";
import { ArrowRight, Check, ChevronDown, Menu, MapPin, MessageCircle, PackageCheck, Phone, ShieldCheck, Truck, X } from "lucide-react";
import { CATALOG, CATEGORIES, HERO_IMAGE, INSTITUTIONAL_IMAGE, AREA_IMAGE, BRANDS, CONTACT_EMAIL, CONTACT_PHONE, WHATSAPP_LINK } from "@/lib/constants";

export function LeadSite() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [quoteSent, setQuoteSent] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const toggle = (item: string) => setSelected((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item]);
  return <>
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-camadel-black/90 backdrop-blur-md">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8">
        <a href="#inicio" className="font-display text-2xl font-bold tracking-tight text-metal"><span className="text-camadel-red">//</span> CAMADEL</a>
        <nav className="hidden items-center gap-7 text-sm text-camadel-silverHi lg:flex">
          {[["Início", "#inicio"], ["Quem somos", "#quem-somos"], ["Catálogo", "#catalogo"], ["Área de atuação", "#area"], ["Contato", "#contato"]].map(([label, href]) => <a key={href} href={href} className="transition-colors hover:text-camadel-red">{label}</a>)}
        </nav>
        <a href="#contato" className="hidden border border-camadel-red bg-camadel-red px-5 py-3 font-display text-sm font-bold uppercase tracking-wide text-white transition hover:bg-transparent hover:text-camadel-red lg:block">Solicitar orçamento</a>
        <button aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)} className="text-camadel-silverHi lg:hidden">{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <nav className="flex flex-col gap-5 border-t border-white/10 bg-camadel-black px-5 py-6 text-sm lg:hidden">{[["Início", "#inicio"], ["Quem somos", "#quem-somos"], ["Catálogo", "#catalogo"], ["Área de atuação", "#area"], ["Contato", "#contato"]].map(([label, href]) => <a onClick={() => setMenuOpen(false)} key={href} href={href}>{label}</a>)}</nav>}
    </header>

    <main id="inicio">
      <section className="relative flex min-h-[720px] items-end overflow-hidden pt-28 lg:min-h-[820px]">
        <img src={HERO_IMAGE} alt="Ferramentas profissionais Camadel em um canteiro de obras" className="absolute inset-0 size-full object-cover object-center" />
        <div className="absolute inset-0 bg-gradient-to-r from-camadel-black via-camadel-black/80 to-camadel-black/20" />
        <div className="relative mx-auto w-full max-w-7xl px-5 pb-16 lg:px-8 lg:pb-24"><div className="max-w-2xl">
          <p className="mb-5 font-mono text-xs uppercase tracking-[0.3em] text-camadel-red">Ferramentas & equipamentos para construção</p>
          <h1 className="font-display text-6xl font-bold uppercase leading-[.92] text-white sm:text-8xl">O prazer no trabalho <span className="text-camadel-red">aperfeiçoa a obra.</span></h1>
          <p className="mt-7 max-w-xl text-lg leading-relaxed text-camadel-silverHi">Soluções completas em ferramentas, máquinas, EPIs, abrasivos, fixação e muito mais para atender sua obra do início ao fim.</p>
          <div className="mt-9 flex flex-wrap gap-4"><a href="#catalogo" className="inline-flex items-center gap-3 bg-camadel-red px-6 py-4 font-display font-bold uppercase tracking-wide text-white hover:bg-camadel-redDark">Conheça nosso catálogo <ArrowRight size={18} /></a><a href="#contato" className="border border-white/40 px-6 py-4 font-display font-bold uppercase tracking-wide text-white hover:border-camadel-red hover:text-camadel-red">Fale com a Camadel</a></div>
        </div></div>
      </section>

      <section className="border-y border-camadel-red/40 bg-camadel-blackLight"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-white/10 lg:grid-cols-4">{[[ShieldCheck,"Qualidade em cada produto"],[PackageCheck,"Estoque completo"],[Truck,"Entrega rápida"],[MessageCircle,"Atendimento especializado"]].map(([Icon, text]) => <div key={text as string} className="flex items-center gap-3 px-5 py-6 lg:px-8"><Icon className="text-camadel-red" size={26}/><span className="font-display text-sm uppercase tracking-wide text-white">{text as string}</span></div>)}</div></section>

      <section id="catalogo" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="mb-12 max-w-2xl"><p className="eyebrow">Linha completa</p><h2 className="section-title">Tudo para sua <span>obra</span></h2><p className="mt-5 text-camadel-silver">Encontre as principais linhas de produtos para construção civil, manutenção industrial e rotina profissional.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{CATEGORIES.map((category) => <a href={`#${category.id}`} key={category.id} className="group relative min-h-64 overflow-hidden border border-white/10 bg-camadel-blackLight"><img src={category.image} alt={category.title} className="absolute inset-0 size-full object-cover opacity-60 transition duration-500 group-hover:scale-105 group-hover:opacity-80"/><div className="absolute inset-0 bg-gradient-to-t from-camadel-black via-camadel-black/50 to-transparent"/><div className="relative flex min-h-64 flex-col justify-end p-5"><p className="font-mono text-xs text-camadel-red">{category.label}</p><h3 className="mt-2 font-display text-2xl font-bold uppercase text-white">{category.title}</h3><span className="mt-4 flex items-center gap-2 text-xs uppercase tracking-widest text-camadel-silverHi">Ver linhas <ArrowRight size={14}/></span></div></a>)}</div></section>

      <section className="bg-camadel-blackLight py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8">{CATALOG.map((group) => <div id={group.id} key={group.id} className="scroll-mt-28 border-t border-white/10 py-12 first:border-t-0"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">{group.label}</p><h3 className="font-display text-3xl font-bold uppercase text-white">{group.title}</h3></div><button onClick={() => group.items.forEach(toggle)} className="text-xs uppercase tracking-widest text-camadel-red hover:text-white">Selecionar todos</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{group.items.map((item) => <button key={item} onClick={() => toggle(item)} className={`flex items-center justify-between border p-4 text-left transition ${selected.includes(item) ? "border-camadel-red bg-camadel-red/10" : "border-white/10 bg-camadel-black hover:border-camadel-red/60"}`}><span className="text-sm text-camadel-silverHi">{item}</span>{selected.includes(item) ? <Check size={17} className="text-camadel-red"/> : <ChevronDown size={16} className="text-camadel-silver"/>}</button>)}</div></div>)}</div></section>

      <section id="quem-somos" className="mx-auto grid max-w-7xl gap-10 px-5 py-24 lg:grid-cols-2 lg:items-center lg:px-8"><div className="relative order-2 overflow-hidden lg:order-1"><img src={INSTITUTIONAL_IMAGE} alt="Profissional utilizando ferramenta elétrica no canteiro" className="aspect-[4/5] w-full object-cover"/><div className="absolute bottom-5 left-5 border border-camadel-red bg-camadel-black/90 px-5 py-4"><p className="font-display text-lg font-bold uppercase text-white">Qualidade, confiança<br/><span className="text-camadel-red">e parceria.</span></p></div></div><div className="order-1 lg:order-2"><p className="eyebrow">Quem somos</p><h2 className="section-title">Parceiro ideal para <span>sua obra</span></h2><p className="mt-6 leading-relaxed text-camadel-silver">A Camadel Ferramentas atua ao longo dos anos de experiência fornecendo materiais para construção civil, dedicando-se a atender seus clientes e parceiros com preços competitivos e o melhor atendimento.</p><p className="mt-4 leading-relaxed text-camadel-silver">Com foco na qualidade dos produtos, nossa equipe está pronta para atender e buscar o que há de melhor no mercado.</p><a href="#contato" className="mt-8 inline-flex items-center gap-3 border-b border-camadel-red pb-2 font-display font-bold uppercase text-white hover:text-camadel-red">Converse com nossa equipe <ArrowRight size={17}/></a></div></section>

      <section id="area" className="bg-camadel-blackLight py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div><p className="eyebrow">Área de atuação</p><h2 className="section-title">Foco na <span>capital paulista</span></h2><p className="mt-6 max-w-xl leading-relaxed text-camadel-silver">Localizados no ABC Paulista, trabalhamos para atender toda a cidade de São Paulo e região metropolitana com soluções completas para as exigências da construção civil.</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{[[MapPin,"São Paulo e região","Atendimento focado na capital paulista."],[Truck,"Entrega rápida","Agilidade para sua obra não parar."],[ShieldCheck,"Parceria e confiança","Relacionamentos sólidos com clientes."],[PackageCheck,"Soluções completas","Tudo o que você precisa em um só lugar."]].map(([Icon,title,text]) => <div key={title as string} className="flex gap-3"><Icon className="shrink-0 text-camadel-red" size={22}/><div><h3 className="font-display uppercase text-white">{title as string}</h3><p className="mt-1 text-sm text-camadel-silver">{text as string}</p></div></div>)}</div></div><img src={AREA_IMAGE} alt="Profissional da construção em São Paulo" className="w-full border border-white/10"/></div></section>

      <section id="contato" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Fale conosco</p><h2 className="section-title">Vamos atender <span>sua obra</span></h2><p className="mt-5 leading-relaxed text-camadel-silver">Conte o que você precisa. Nossa equipe comercial retorna com uma solução adequada para sua operação.</p><div className="mt-9 flex flex-col gap-5 text-camadel-silverHi"><a href={WHATSAPP_LINK} className="flex items-center gap-3 hover:text-camadel-red"><MessageCircle className="text-camadel-red"/> {CONTACT_PHONE}</a><a href={`mailto:${CONTACT_EMAIL}`} className="flex items-center gap-3 hover:text-camadel-red"><Phone className="text-camadel-red"/> {CONTACT_EMAIL}</a><p className="flex items-center gap-3"><MapPin className="text-camadel-red"/> ABC Paulista, São Paulo</p></div></div><form onSubmit={(event) => { event.preventDefault(); setQuoteSent(true); }} className="border border-white/10 bg-camadel-blackLight p-6 lg:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="flex flex-col gap-2 text-sm text-camadel-silverHi">Nome<input required className="border border-white/15 bg-camadel-black px-4 py-3 text-white outline-none focus:border-camadel-red" placeholder="Seu nome"/></label><label className="flex flex-col gap-2 text-sm text-camadel-silverHi">WhatsApp<input required className="border border-white/15 bg-camadel-black px-4 py-3 text-white outline-none focus:border-camadel-red" placeholder="(11) 99999-9999"/></label><label className="flex flex-col gap-2 text-sm text-camadel-silverHi sm:col-span-2">E-mail corporativo<input type="email" required className="border border-white/15 bg-camadel-black px-4 py-3 text-white outline-none focus:border-camadel-red" placeholder="voce@empresa.com.br"/></label><label className="flex flex-col gap-2 text-sm text-camadel-silverHi sm:col-span-2">O que sua obra precisa?<textarea required rows={4} className="resize-none border border-white/15 bg-camadel-black px-4 py-3 text-white outline-none focus:border-camadel-red" placeholder={selected.length ? `Itens selecionados: ${selected.join(", ")}` : "Descreva produtos, quantidades ou aplicação"}/></label></div><button className="mt-6 flex w-full items-center justify-center gap-3 bg-camadel-red px-5 py-4 font-display font-bold uppercase tracking-wide text-white hover:bg-camadel-redDark">{quoteSent ? "Solicitação enviada" : "Enviar solicitação"} <ArrowRight size={18}/></button>{quoteSent && <p className="mt-4 text-center text-sm text-camadel-red">Recebemos seus dados. Nossa equipe entrará em contato.</p>}</form></div></section>
    </main>
    <footer className="border-t border-camadel-red/50 bg-camadel-blackLight"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm text-camadel-silver lg:flex-row lg:items-center lg:justify-between lg:px-8"><p className="font-display text-xl font-bold text-metal"><span className="text-camadel-red">//</span> CAMADEL</p><p>Ferramentas para construção</p><p>© {new Date().getFullYear()} Camadel. Todos os direitos reservados.</p></div></footer>
    <a href={WHATSAPP_LINK} aria-label="Falar com a Camadel pelo WhatsApp" className="fixed bottom-6 right-6 z-40 flex size-14 items-center justify-center rounded-full bg-camadel-red text-white shadow-lg shadow-camadel-red/30 transition hover:scale-105"><MessageCircle size={27}/></a>
  </>;
}

export default LeadSite;
